"""Telegram session, shared links, groups

Revision ID: 0e43c3d7aa59
Revises: 09982efded97
Create Date: 2026-08-15 14:51:28.269190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e43c3d7aa59'
down_revision: Union[str, Sequence[str], None] = '09982efded97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.Column('revoked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shared_links_folder_id', 'shared_links', ['folder_id'], unique=False)
    op.create_index('ix_shared_links_message_id', 'shared_links', ['message_id'], unique=False)
    op.create_table('tg_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('session_string', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_sessions_id'), 'tg_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_tg_sessions_name'), 'tg_sessions', ['name'], unique=True)
    op.drop_index('ix_api_keys_id', table_name='api_keys')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='api_keys_pkey')
    )
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=True)
    op.create_index('ix_api_keys_id', 'api_keys', ['id'], unique=False)
    op.drop_index(op.f('ix_tg_sessions_name'), table_name='tg_sessions')
    op.drop_index(op.f('ix_tg_sessions_id'), table_name='tg_sessions')
    op.drop_table('tg_sessions')
    op.drop_index('ix_shared_links_message_id', table_name='shared_links')
    op.drop_index('ix_shared_links_folder_id', table_name='shared_links')
    op.drop_table('shared_links')
    op.drop_table('groups')
    # ### end Alembic commands ###
