"""Shared link owner user_id

Revision ID: 197d0b8384fc
Revises: e80cb1d0eb30
Create Date: 2026-08-15 16:27:37.678245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197d0b8384fc'
down_revision: Union[str, Sequence[str], None] = 'e80cb1d0eb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_links', sa.Column('user_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_links', 'user_id')
    # ### end Alembic commands ###
