"""folder and file ownership

Revision ID: 8e56bfb3a8c3
Revises: 197d0b8384fc
Create Date: 2026-08-17 10:00:43.941334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e56bfb3a8c3'
down_revision: Union[str, Sequence[str], None] = '197d0b8384fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Set default owner_user_id = 0 cho dữ liệu cũ trước khi thêm NOT NULL
    op.add_column('folders', sa.Column('owner_user_id', sa.Integer(), nullable=True, server_default='0'))
    op.execute('UPDATE folders SET owner_user_id = 0 WHERE owner_user_id IS NULL')
    op.alter_column('folders', 'owner_user_id', nullable=False, server_default=None)
    op.create_index(op.f('ix_folders_owner_user_id'), 'folders', ['owner_user_id'], unique=False)

    op.add_column('files', sa.Column('owner_user_id', sa.Integer(), nullable=True, server_default='0'))
    op.execute('UPDATE files SET owner_user_id = 0 WHERE owner_user_id IS NULL')
    op.alter_column('files', 'owner_user_id', nullable=False, server_default=None)
    op.create_index(op.f('ix_files_owner_user_id'), 'files', ['owner_user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_owner_user_id'), table_name='folders')
    op.drop_column('folders', 'owner_user_id')
    op.drop_index(op.f('ix_files_owner_user_id'), table_name='files')
    op.drop_column('files', 'owner_user_id')
    # ### end Alembic commands ###
