"""Per-user telegram sessions

Revision ID: e80cb1d0eb30
Revises: 0e43c3d7aa59
Create Date: 2026-08-15 16:21:47.361791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80cb1d0eb30'
down_revision: Union[str, Sequence[str], None] = '0e43c3d7aa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Xóa dữ liệu session cũ (không thể map sang user)
    op.execute('DELETE FROM tg_sessions')
    op.add_column('tg_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_tg_sessions_name', table_name='tg_sessions')
    op.create_index(op.f('ix_tg_sessions_user_id'), 'tg_sessions', ['user_id'], unique=True)
    op.drop_column('tg_sessions', 'name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_sessions', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tg_sessions_user_id'), table_name='tg_sessions')
    op.create_index('ix_tg_sessions_name', 'tg_sessions', ['name'], unique=True)
    op.drop_column('tg_sessions', 'user_id')
    # ### end Alembic commands ###
